-- Add all bePaid export fields to payment_reconcile_queue
ALTER TABLE payment_reconcile_queue 
  ADD COLUMN IF NOT EXISTS bepaid_order_id text,
  ADD COLUMN IF NOT EXISTS status_normalized text,
  ADD COLUMN IF NOT EXISTS transaction_type text,
  ADD COLUMN IF NOT EXISTS fee_percent numeric,
  ADD COLUMN IF NOT EXISTS fee_amount numeric,
  ADD COLUMN IF NOT EXISTS total_fee numeric,
  ADD COLUMN IF NOT EXISTS transferred_amount numeric,
  ADD COLUMN IF NOT EXISTS created_at_bepaid timestamp with time zone,
  ADD COLUMN IF NOT EXISTS transferred_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS valid_until timestamp with time zone,
  ADD COLUMN IF NOT EXISTS message text,
  ADD COLUMN IF NOT EXISTS shop_id text,
  ADD COLUMN IF NOT EXISTS shop_name text,
  ADD COLUMN IF NOT EXISTS business_category text,
  ADD COLUMN IF NOT EXISTS customer_name text,
  ADD COLUMN IF NOT EXISTS customer_surname text,
  ADD COLUMN IF NOT EXISTS customer_address text,
  ADD COLUMN IF NOT EXISTS customer_country text,
  ADD COLUMN IF NOT EXISTS customer_city text,
  ADD COLUMN IF NOT EXISTS customer_zip text,
  ADD COLUMN IF NOT EXISTS customer_state text,
  ADD COLUMN IF NOT EXISTS customer_phone text,
  ADD COLUMN IF NOT EXISTS card_last4 text,
  ADD COLUMN IF NOT EXISTS card_holder text,
  ADD COLUMN IF NOT EXISTS card_brand text,
  ADD COLUMN IF NOT EXISTS card_valid_until text,
  ADD COLUMN IF NOT EXISTS card_bin text,
  ADD COLUMN IF NOT EXISTS card_bank text,
  ADD COLUMN IF NOT EXISTS card_bank_country text,
  ADD COLUMN IF NOT EXISTS payment_method text,
  ADD COLUMN IF NOT EXISTS product_code text,
  ADD COLUMN IF NOT EXISTS three_d_secure boolean,
  ADD COLUMN IF NOT EXISTS avs_result text,
  ADD COLUMN IF NOT EXISTS fraud_result text,
  ADD COLUMN IF NOT EXISTS reason text;